name: CI Full-Stack Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        # Force le checkout à la racine du workspace du runner (pas de sous-dossier TP-Git-Pratique supplémentaire)
        path: ./ 

    - name: Setup Node.js (Backend & Frontend)
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Installation et Test du Backend (API Catalogue)
      # Maintenant, ce chemin simple fonctionnera car 'mini-api-catalogue' est à la racine
      working-directory: mini-api-catalogue 
      run: |
        npm install

    - name: Installation et Build du Frontend (React Client)
      # Ce chemin simple fonctionnera aussi
      working-directory: react-client 
      run: |
        npm install
        npm run build







