name: CI Full-Stack Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js (Backend & Frontend)
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Version LTS stable de Node.js

    - name: Installation et Test du Backend (API Catalogue)
      working-directory: ./mini-api-catalogue
      run: |
        npm install
        # Les tests unitaires (s'ils existent) seraient exécutés ici, ex: npm test

    - name: Installation et Build du Frontend (React Client)
      working-directory: ./react-client
      run: |
        npm install
        # Exécute la commande de build de Vite pour vérifier que le projet compile
        npm run build
        # Les tests unitaires (s'ils existent) seraient exécutés ici, ex: npm test



