name: CI Full-Stack Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        # Assure le clonage Ã  la racine du workspace du runner
        path: ./

    - name: Setup Node.js (Backend & Frontend)
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Installation et Test du Backend (API Catalogue)
      # Utilise le chemin absolu pour garantir la localisation correcte
      working-directory: ${{ github.workspace }}/mini-api-catalogue 
      run: |
        npm install

    - name: Installation et Build du Frontend (React Client)
      # Utilise le chemin absolu pour garantir la localisation correcte
      working-directory: ${{ github.workspace }}/react-client
      run: |
        npm install
        npm run build










